name: 'Run tests'

on:
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  Format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
      - name: Format code
        run: yarn prettify
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: ':robot: Automated code formatting'
          branch: 'master'
  Build-And-Test:
    needs: Format-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test:ci
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          verbose: true
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage/
